# Generated by Django 5.0.2 on 2024-12-04 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_code', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('phone_number', models.CharField(max_length=13)),
                ('postal_code', models.CharField(max_length=8)),
                ('address', models.CharField(max_length=40)),
                ('discount_rate', models.PositiveSmallIntegerField()),
                ('delete_flag', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='CustomerNumbering',
            fields=[
                ('customer_code', models.PositiveIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'customer_numbering',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_number', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=6)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_code', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('price', models.PositiveIntegerField()),
                ('stock', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'item',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_number', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('total_amount', models.PositiveIntegerField()),
                ('detail_count', models.PositiveSmallIntegerField()),
                ('delivery_date', models.DateField()),
                ('order_date', models.DateField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psys.customer')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psys.employee')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_quantity', models.PositiveIntegerField()),
                ('order_amount', models.PositiveIntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psys.item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psys.orders')),
            ],
            options={
                'db_table': 'order_details',
                'unique_together': {('order', 'item')},
            },
        ),
    ]
