# Generated by Django 5.0.2 on 2025-01-08 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psys', '0002_delete_authgroup_delete_authgrouppermissions_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderdetails',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='item',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='detail_count',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='item',
            name='delete_flag',
            field=models.BooleanField(default=False, verbose_name='削除フラグ'),
        ),
        migrations.AddField(
            model_name='item',
            name='stock_quantity',
            field=models.IntegerField(default=0, verbose_name='在庫数'),
        ),
        migrations.AddField(
            model_name='orders',
            name='delete_flag',
            field=models.BooleanField(default=False, verbose_name='削除フラグ'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='住所'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='得意先コード'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_name',
            field=models.CharField(max_length=100, verbose_name='得意先名'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_postalcode',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='郵便番号'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_telno',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='電話番号'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='delete_flag',
            field=models.BooleanField(default=False, verbose_name='削除フラグ'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='discount_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='割引率'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_code',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='商品コード'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_name',
            field=models.CharField(max_length=100, verbose_name='商品名'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(default=0, verbose_name='単価'),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='psys.item', verbose_name='商品'),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='order_quantity',
            field=models.IntegerField(default=0, verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='psys.customer', verbose_name='得意先'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='納期'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_date',
            field=models.DateField(auto_now_add=True, verbose_name='受注日'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_number',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='受注番号'),
        ),
        migrations.AlterModelTable(
            name='customer',
            table=None,
        ),
        migrations.AlterModelTable(
            name='item',
            table=None,
        ),
        migrations.AlterModelTable(
            name='orderdetails',
            table=None,
        ),
        migrations.AlterModelTable(
            name='orders',
            table=None,
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='order_amount',
        ),
    ]
