# Generated by Django 5.0.2 on 2025-01-08 06:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psys', '0003_alter_orderdetails_unique_together_remove_item_stock_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name': '受注', 'verbose_name_plural': '受注'},
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='受注日'),
        ),
    ]
