# Generated by Django 5.0.2 on 2025-01-22 05:02

from django.db import migrations, models


def create_initial_customers(apps, schema_editor):
    Customer = apps.get_model('psys', 'Customer')
    initial_customers = [
        {
            'customer_code': 'RA0001',
            'customer_name': 'A ストア',
            'customer_telno': '045-128-3581',
            'customer_postalcode': '220-0001',
            'customer_address': '大阪市北区北幸２－１',
            'discount_rate': 0,
            'delete_flag': False
        },
        {
            'customer_code': 'RA0002',
            'customer_name': 'B ストア',
            'customer_telno': '045-128-3582',
            'customer_postalcode': '220-0002',
            'customer_address': '大阪市北区浅間２－２',
            'discount_rate': 0,
            'delete_flag': False
        },
        {
            'customer_code': 'RA0003',
            'customer_name': 'C ストア',
            'customer_telno': '045-128-3583',
            'customer_postalcode': '220-0003',
            'customer_address': '大阪市北区梅田２－１',
            'discount_rate': 0,
            'delete_flag': False
        },
        {
            'customer_code': 'RA0004',
            'customer_name': 'D ストア',
            'customer_telno': '045-128-3584',
            'customer_postalcode': '220-0004',
            'customer_address': '大阪市北区南幸１－４',
            'discount_rate': 0,
            'delete_flag': False
        },
        {
            'customer_code': 'RA0005',
            'customer_name': 'E ストア',
            'customer_telno': '045-128-3585',
            'customer_postalcode': '220-0005',
            'customer_address': '大阪市北区北幸２－５',
            'discount_rate': 0,
            'delete_flag': False
        },
        {
            'customer_code': 'RA0006',
            'customer_name': 'F ストア',
            'customer_telno': '045-128-3586',
            'customer_postalcode': '220-0006',
            'customer_address': '大阪市北区北幸２－６',
            'discount_rate': 0,
            'delete_flag': False
        },
        {
            'customer_code': 'RA0007',
            'customer_name': 'G ストア',
            'customer_telno': '045-128-3587',
            'customer_postalcode': '220-0007',
            'customer_address': '大阪市北区高島１－１',
            'discount_rate': 0,
            'delete_flag': False
        },
        {
            'customer_code': 'RA0008',
            'customer_name': 'H ストア',
            'customer_telno': '045-128-3588',
            'customer_postalcode': '220-0008',
            'customer_address': '大阪市北区高島１－２',
            'discount_rate': 0,
            'delete_flag': False
        },
        {
            'customer_code': 'RA0009',
            'customer_name': 'I ストア',
            'customer_telno': '045-128-3589',
            'customer_postalcode': '220-0009',
            'customer_address': '大阪市北区高島２－３',
            'discount_rate': 0,
            'delete_flag': False
        },
        {
            'customer_code': 'RA0010',
            'customer_name': 'J ストア',
            'customer_telno': '045-150-3590',
            'customer_postalcode': '220-0010',
            'customer_address': '大阪市北区高島２－４',
            'discount_rate': 0,
            'delete_flag': False
        },
        {
            'customer_code': 'RA0011',
            'customer_name': 'K ストア',
            'customer_telno': '045-150-3591',
            'customer_postalcode': '220-0011',
            'customer_address': '大阪市北区梅田２－１',
            'discount_rate': 0,
            'delete_flag': False
        },
        {
            'customer_code': 'RA0012',
            'customer_name': 'L ストア',
            'customer_telno': '045-150-3592',
            'customer_postalcode': '220-0012',
            'customer_address': '大阪市北区梅田２－２',
            'discount_rate': 0,
            'delete_flag': False
        },
        {
            'customer_code': 'RA0013',
            'customer_name': 'M ストア',
            'customer_telno': '045-150-3593',
            'customer_postalcode': '220-0013',
            'customer_address': '大阪市北区梅田２－３',
            'discount_rate': 0,
            'delete_flag': False
        },
        {
            'customer_code': 'RA0014',
            'customer_name': 'N ストア',
            'customer_telno': '045-150-3594',
            'customer_postalcode': '220-0014',
            'customer_address': '大阪市北区梅田２－４',
            'discount_rate': 0,
            'delete_flag': False
        },
        {
            'customer_code': 'RA0015',
            'customer_name': 'O ストア',
            'customer_telno': '045-150-3595',
            'customer_postalcode': '220-0015',
            'customer_address': '大阪市北区梅田２－５',
            'discount_rate': 0,
            'delete_flag': False
        },
    ]

    for customer_data in initial_customers:
        Customer.objects.create(**customer_data)

def delete_initial_customers(apps, schema_editor):
    Customer = apps.get_model('psys', 'Customer')
    Customer.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('psys', '0004_alter_orders_options_alter_orders_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterModelTable(
            name='employee',
            table=None,
        ),
        migrations.RunPython(create_initial_customers, delete_initial_customers),
    ]
